[project]
name = 'curly_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.impact_repo]
path = 'contracts/impact_repo.clar'
clarity_version = 2
epoch = 2.5

[contracts.loan_contract]
path = 'contracts/loan_contract.clar'
clarity_version = 2
epoch = 2.5

[contracts.research]
path = 'contracts/research.clar'
clarity_version = 2
epoch = 2.5

[contracts.stockroom_with_multiple_keys]
path = 'contracts/stockroom_with_multiple_keys.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
